server:
  port: 8090
  error:
    path: /error

spring:
  datasource:
    main:
      #url: jdbc:h2:file:./kgd
      url: jdbc:postgresql://localhost:5430/demoDB
      username: test
      password: test
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      generate-ddl: false
  flyway:
    enabled: false
    main:
      enabled: true
      #locations: classpath:db/migration/main/h2
      locations: classpath:db/migration/main/postgre
      baseline-on-migrate: true

api:
  doc_per_page: 10

springdoc:
  api-docs:
    path: "/swagger-ui"

logging:
  level:
    root: warn
    ru.igorit.andrk: info
    org.springframework.boot.web.embedded.tomcat: info
    org.flywaydb.core.internal.license: fatal
    org.flywaydb.core.internal.database: info

